CS_Names = {...
'Eduardo Alonso',...
'Gennady Andrienko',...
'Natalia Andrienko',...
'Belen Barros Pena',...
'Peter Bishop',...
'Robin Bloomfield',...
'Daniel Chicharro',...
'Chris Child',...
'Laure Daviaud',...
'Jason Dykes',...
'Cristina Gacek',...
'Artur d''Avila Garcez',...
'Michael Garcia Ortiz',...
'Ilir Gashi',...
'Panos Giannopoulos',...
'Sara Heitlinger',...
'Jacob Howe',...
'Sebastian Hunt',...
'Radu Jianu',...
'Elahe Kane-Zabihi',...
'Cefa Karabag',...
'Christos Kloukinas',...
'Nikos Komninos',...
'Michal Krol',...
'Bev Littlewood',...
'Andrew Macfarlane',...
'Pranava Madhyastha',...
'Stephann Makri',...
'Esther Mondragon',...
'Martin Nyx Brain',...
'Ross Patterson',...
'Peter Popov',...
'Andrey Povyakalo',...
'Ernesto Priego',...
'Constantino Carlos Reyes-Aldasoro',...
'Ernesto Jimenez-Ruiz',...
'Kizito Salako',...
'Aidan Slingsby',...
'Peter Smith',...
'George Spanoudakis',...
'Vladimir Stankovic',...
'Lorenzo Strigini',...
'Giacomo Tarroni',...
'Alex Taylor',...
'Aram Ter-Sarkisov',...
'Tillman Weyde',...
'Stephanie Wilson',...
'Joseph Wood'};

CS_LastNames = {...
'Alonso,E',...
'Andrienko',...
'Andrienko',...
'Barros Pena',...
'Bishop',...
'Bloomfield',...
'Chicharro',...
'Child',...
'Daviaud',...
'Dykes',...
'Gacek',...
'd''Avila Garcez',...
'Garcia Ortiz',...
'Gashi',...
'Giannopoulos',...
'Heitlinger',...
'Howe',...
'Hunt',...
'Jianu',...
'Kane-Zabihi',...
'Karabag',...
'Kloukinas',...
'Komninos',...
'Krol',...
'Littlewood',...
'Macfarlane',...
'Madhyastha',...
'Makri',...
'Mondragon',...
'Nyx Brain',...
'Patterson',...
'Popov',...
'Povyakalo',...
'Priego',...
'Reyes-Aldasoro',...
'Jimenez-Ruiz',...
'Salako',...
'Slingsby',...
'Smith,P',...
'Spanoudakis',...
'Stankovic',...
'Strigini',...
'Tarroni',...
'Taylor',...
'Ter-Sarkisov',...
'Weyde',...
'Wilson',...
'Wood'};
